spring.application.name=Note-Vault
spring.datasource.url=jdbc:mysql://localhost:3306/notevault
spring.datasource.username=root
spring.datasource.password=Aryan@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

